### ISSUE TITLE
Feature Request: Support dynamic vectors and matrices

### ISSUE THREAD

**Issue by dzimmanck** [AzeezDa/eqsolver#3] opened 2023-02-24 23:15 UTC
The input signature for the solvers enforces use of vectors and matrices which are known at compile time rather than runtime, which limits use cases.  It would be nice if the solvers would accept both S and D style matrices and vectors.

```rust
use eqsolver::multivariable::MultiVarNewton;
use nalgebra::{DVector, DMatrix};

// function
let f = |v: DVector<f64>| DVector::from_vec(vec![v[0].powi(2) + v[1] - 11., v[0] + v[1].powi(2) - 7.]);

// jacobian
let j = |v: DVector<f64>| DMatrix::from_vec(2, 2, vec![2. * v[0], 1., 1., 2. * v[1]]);

let initial_guess = DVector::from_vec(vec![1., 1.]);

// this does not work
let solution = MultiVarNewton::new(f, j)
    .with_tol(1e-5)
    .with_itermax(50)
    .solve(initial_guess)
    .unwrap();
```

**Comment by AzeezDa** [comment] 2023-03-19 21:39
Hello @dzimmanck! I have been busy the last few weeks so I just had to time implement this!

After looking at and researching the Nalgebra library I implemented support for the DVector and DMatrix. It can be found on the [`dvector-support`](https://github.com/AzeezDa/eqsolver/tree/dvector-support) branch.

(There still are small things that need fine-tuning and cleaning to be done, but the code in the [`dvector-support`](https://github.com/AzeezDa/eqsolver/tree/dvector-support) branch worked for all tests including one similar to the one you provided)

Please do tell me if something seems off or not working as intended 😃

**Comment by alissapajer** [comment] 2023-06-05 20:53
I have a use case that requires this feature. @AzeezDa could you merge this into `master` and release (or release just the branch)? Thanks!

**Comment by AzeezDa** [comment] 2023-06-06 06:46
@alissapajer The `dvector-support` branch has been tested, merged into `master` and updated on Crates.io with version `0.1.2`.

Please let me know if any issues arise!

**Closed by AzeezDa** 2023-06-06 06:46 UTC
Labels: enhancement
